-- JournalAnalyzer: journal_entry table (separate from Traffic-Predictor traffic/event)
-- Run in Supabase SQL Editor or via MCP apply_migration
-- Matches columns in journal_entries.csv

CREATE TABLE IF NOT EXISTS journal_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_date DATE NOT NULL,
  day_of_week TEXT NOT NULL,
  time_of_day TEXT NOT NULL,
  text TEXT NOT NULL
);

-- Index for time-range filters in the Shiny app
CREATE INDEX IF NOT EXISTS idx_journal_entry_entry_date ON journal_entry (entry_date);

COMMENT ON TABLE journal_entry IS 'Journal Analyzer diary entries; isolated from traffic/event tables.';
